//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFAchievementManagerEx.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFAchievementManagerEx.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1}: 无需修改该项成就 的本地化字符串。
        /// </summary>
        internal static string AchievementChangeUnnecessary {
            get {
                return ResourceManager.GetString("AchievementChangeUnnecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 无效参数, 需要为整数 的本地化字符串。
        /// </summary>
        internal static string AchievementIdInvalid {
            get {
                return ResourceManager.GetString("AchievementIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1}: 无法修改被保护的成就 的本地化字符串。
        /// </summary>
        internal static string AchievementIsProtected {
            get {
                return ResourceManager.GetString("AchievementIsProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - {0,-3} {1} {2}{3} 的本地化字符串。
        /// </summary>
        internal static string AchievementItem {
            get {
                return ResourceManager.GetString("AchievementItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App/{0} 的成就列表: 的本地化字符串。
        /// </summary>
        internal static string AchievementList {
            get {
                return ResourceManager.GetString("AchievementList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 找不到此ID的成就 的本地化字符串。
        /// </summary>
        internal static string AchievementNotFounf {
            get {
                return ResourceManager.GetString("AchievementNotFounf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已经是最新版本, 无需更新插件 的本地化字符串。
        /// </summary>
        internal static string AlreadyLatest {
            get {
                return ResourceManager.GetString("AlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 参数值不能为 {1} 的本地化字符串。
        /// </summary>
        internal static string ArgsInvalid {
            get {
                return ResourceManager.GetString("ArgsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数为空 的本地化字符串。
        /// </summary>
        internal static string ArgsIsEmpty {
            get {
                return ResourceManager.GetString("ArgsIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ASFECurrentVersion {
            get {
                return ResourceManager.GetString("ASFECurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ASFEOnlineVersion {
            get {
                return ResourceManager.GetString("ASFEOnlineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 插件版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ASFEPluginVersion {
            get {
                return ResourceManager.GetString("ASFEPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令 AAMUPDATE / AAMU 自动更新插件 的本地化字符串。
        /// </summary>
        internal static string ASFEUpdateTips {
            get {
                return ResourceManager.GetString("ASFEUpdateTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令 AAMVERSION / AAMV 检查插件更新 的本地化字符串。
        /// </summary>
        internal static string ASFEVersionTips {
            get {
                return ResourceManager.GetString("ASFEVersionTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 附件:  的本地化字符串。
        /// </summary>
        internal static string Assert {
            get {
                return ResourceManager.GetString("Assert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份已经自动清理 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackup {
            get {
                return ResourceManager.GetString("CleanUpOldBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份清理失败 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackupFailed {
            get {
                return ResourceManager.GetString("CleanUpOldBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令 {0} 被禁用! 的本地化字符串。
        /// </summary>
        internal static string CommandDisabled {
            get {
                return ResourceManager.GetString("CommandDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-Hans 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 描述: {0} 的本地化字符串。
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载插件失败! 的本地化字符串。
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - Access: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogAccess {
            get {
                return ResourceManager.GetString("ErrorLogAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - ASF 版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogASFVersion {
            get {
                return ResourceManager.GetString("ErrorLogASFVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 错误消息: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogErrorMessage {
            get {
                return ResourceManager.GetString("ErrorLogErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 错误类型: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogErrorName {
            get {
                return ResourceManager.GetString("ErrorLogErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 原始消息: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogOriginMessage {
            get {
                return ResourceManager.GetString("ErrorLogOriginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 插件版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogPluginVersion {
            get {
                return ResourceManager.GetString("ErrorLogPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFenhance 遇到错误, 日志如下 的本地化字符串。
        /// </summary>
        internal static string ErrorLogTitle {
            get {
                return ResourceManager.GetString("ErrorLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未同意 ASFEnhance.EULA , 该命令不可用 的本地化字符串。
        /// </summary>
        internal static string EulaCmdUnavilable {
            get {
                return ResourceManager.GetString("EulaCmdUnavilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 尚未同意 EULA , 部分命令已禁用 的本地化字符串。
        /// </summary>
        internal static string EulaWarning {
            get {
                return ResourceManager.GetString("EulaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行结果: 的本地化字符串。
        /// </summary>
        internal static string ExecuteResult {
            get {
                return ResourceManager.GetString("ExecuteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 App/{0} 的成就数据失败 的本地化字符串。
        /// </summary>
        internal static string GetAchievementDataFailure {
            get {
                return ResourceManager.GetString("GetAchievementDataFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取插件发行版信息失败! 的本地化字符串。
        /// </summary>
        internal static string GetReleaseInfoFailed {
            get {
                return ResourceManager.GetString("GetReleaseInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部错误 的本地化字符串。
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 schinese 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}({1}) 的本地化字符串。
        /// </summary>
        internal static string MaxChange {
            get {
                return ResourceManager.GetString("MaxChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多行结果: 的本地化字符串。
        /// </summary>
        internal static string MultipleLineResult {
            get {
                return ResourceManager.GetString("MultipleLineResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络错误 的本地化字符串。
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无待设置的成就 的本地化字符串。
        /// </summary>
        internal static string NoAchievementEffected {
            get {
                return ResourceManager.GetString("NoAchievementEffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无参数 的本地化字符串。
        /// </summary>
        internal static string NoArgs {
            get {
                return ResourceManager.GetString("NoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无待设置的统计项 的本地化字符串。
        /// </summary>
        internal static string NoStatsEffected {
            get {
                return ResourceManager.GetString("NoStatsEffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML解析失败! 的本地化字符串。
        /// </summary>
        internal static string ParseHtmlFailed {
            get {
                return ResourceManager.GetString("ParseHtmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 Rudokhvist, Chr_, 联系方式 chr@chrxw.com 的本地化字符串。
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱发电: https://afdian.net/@chr233 的本地化字符串。
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 版本 {1} 的本地化字符串。
        /// </summary>
        internal static string PluginVer {
            get {
                return ResourceManager.GetString("PluginVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置成就{0}, 受影响成就 {1} 个 的本地化字符串。
        /// </summary>
        internal static string SetAchievementResult {
            get {
                return ResourceManager.GetString("SetAchievementResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置统计项{0}, 受影响统计项 {1} 个 的本地化字符串。
        /// </summary>
        internal static string SetStatsResult {
            get {
                return ResourceManager.GetString("SetStatsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 无效参数, 格式为n=x, n为整数, x为整数或d/default(默认值)或i/min(最小值)或a/max(最大值) 的本地化字符串。
        /// </summary>
        internal static string StatsArgumentInvalid {
            get {
                return ResourceManager.GetString("StatsArgumentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无法设置为默认值, 默认值为Null 的本地化字符串。
        /// </summary>
        internal static string StatsCantSetToDefault {
            get {
                return ResourceManager.GetString("StatsCantSetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无法设置为最大值, 最大值为Null 的本地化字符串。
        /// </summary>
        internal static string StatsCantSetToMax {
            get {
                return ResourceManager.GetString("StatsCantSetToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无法设置为最小值, 最小值为Null 的本地化字符串。
        /// </summary>
        internal static string StatsCantSetToMin {
            get {
                return ResourceManager.GetString("StatsCantSetToMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无需更改的统计项 的本地化字符串。
        /// </summary>
        internal static string StatsChangeUnnecessary {
            get {
                return ResourceManager.GetString("StatsChangeUnnecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 具有递增限制的统计项无法设置为更低的值 {3} 的本地化字符串。
        /// </summary>
        internal static string StatsIncrementOnlyLimited {
            get {
                return ResourceManager.GetString("StatsIncrementOnlyLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无法修改被保护的统计项 的本地化字符串。
        /// </summary>
        internal static string StatsIsProtected {
            get {
                return ResourceManager.GetString("StatsIsProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - {0,-3} [{1}] {2}{3}{4}{5} 的本地化字符串。
        /// </summary>
        internal static string StatsItem {
            get {
                return ResourceManager.GetString("StatsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App/{0} 的统计数据列表: 的本地化字符串。
        /// </summary>
        internal static string StatsList {
            get {
                return ResourceManager.GetString("StatsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 设定的值 {3} 超过了最大该变量 {4}, 修改为允许的上/下限 的本地化字符串。
        /// </summary>
        internal static string StatsMaxChangeLimited {
            get {
                return ResourceManager.GetString("StatsMaxChangeLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 找不到此统计项ID 的本地化字符串。
        /// </summary>
        internal static string StatsNotFound {
            get {
                return ResourceManager.GetString("StatsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无法设置为{3}, 参数需要为整数 的本地化字符串。
        /// </summary>
        internal static string StatsTargetValueInvalid {
            get {
                return ResourceManager.GetString("StatsTargetValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Id  [最小 当前 最大] 名称 | 🔒受保护🔼仅能增加⚠️最大修改量 的本地化字符串。
        /// </summary>
        internal static string StatsTitle {
            get {
                return ResourceManager.GetString("StatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 链接: {0} 的本地化字符串。
        /// </summary>
        internal static string SubLink {
            get {
                return ResourceManager.GetString("SubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 名称: {0} 的本地化字符串。
        /// </summary>
        internal static string SubName {
            get {
                return ResourceManager.GetString("SubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 尺寸: {0:0.000} KB 的本地化字符串。
        /// </summary>
        internal static string SubSize {
            get {
                return ResourceManager.GetString("SubSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新失败, 压缩包内容解析失败 的本地化字符串。
        /// </summary>
        internal static string UpdateFiledWithZip {
            get {
                return ResourceManager.GetString("UpdateFiledWithZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新完成, 重启ASF即可应用, 如果不兼容请更新ASF版本 的本地化字符串。
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以使用命令 AAMUPDATE / AAMU 自动更新插件 的本地化字符串。
        /// </summary>
        internal static string UpdateTips {
            get {
                return ResourceManager.GetString("UpdateTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 版本: {0} 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告信息: 的本地化字符串。
        /// </summary>
        internal static string WarningInfo {
            get {
                return ResourceManager.GetString("WarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
