//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFAchievementManagerEx.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFAchievementManagerEx.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1}: 无需修改该项成就 的本地化字符串。
        /// </summary>
        internal static string AchievementChangeUnnecessary {
            get {
                return ResourceManager.GetString("AchievementChangeUnnecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 无效参数, 需要为整数 的本地化字符串。
        /// </summary>
        internal static string AchievementIdInvalid {
            get {
                return ResourceManager.GetString("AchievementIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1}: 无法修改被保护的成就 的本地化字符串。
        /// </summary>
        internal static string AchievementIsProtected {
            get {
                return ResourceManager.GetString("AchievementIsProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - {0,-3} {1} {2}{3} 的本地化字符串。
        /// </summary>
        internal static string AchievementItem {
            get {
                return ResourceManager.GetString("AchievementItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App/{0} 的成就列表: 的本地化字符串。
        /// </summary>
        internal static string AchievementList {
            get {
                return ResourceManager.GetString("AchievementList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 找不到此ID的成就 的本地化字符串。
        /// </summary>
        internal static string AchievementNotFounf {
            get {
                return ResourceManager.GetString("AchievementNotFounf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 参数值不能为 {1} 的本地化字符串。
        /// </summary>
        internal static string ArgsInvalid {
            get {
                return ResourceManager.GetString("ArgsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数为空 的本地化字符串。
        /// </summary>
        internal static string ArgsIsEmpty {
            get {
                return ResourceManager.GetString("ArgsIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册失败 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterFailed {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册成功 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterSuccess {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令 {0} 被禁用! 的本地化字符串。
        /// </summary>
        internal static string CommandDisabled {
            get {
                return ResourceManager.GetString("CommandDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-Hans 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🔼 的本地化字符串。
        /// </summary>
        internal static string EmojiIncrementOnly {
            get {
                return ResourceManager.GetString("EmojiIncrementOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🔒 的本地化字符串。
        /// </summary>
        internal static string EmojiLock {
            get {
                return ResourceManager.GetString("EmojiLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ❌ 的本地化字符串。
        /// </summary>
        internal static string EmojiNo {
            get {
                return ResourceManager.GetString("EmojiNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️ 的本地化字符串。
        /// </summary>
        internal static string EmojiWarning {
            get {
                return ResourceManager.GetString("EmojiWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ✅ 的本地化字符串。
        /// </summary>
        internal static string EmojiYes {
            get {
                return ResourceManager.GetString("EmojiYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未同意 ASFEnhance.EULA , 该命令不可用 的本地化字符串。
        /// </summary>
        internal static string EulaCmdUnavilable {
            get {
                return ResourceManager.GetString("EulaCmdUnavilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 尚未同意 EULA , 部分命令已禁用 的本地化字符串。
        /// </summary>
        internal static string EulaWarning {
            get {
                return ResourceManager.GetString("EulaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行结果: 的本地化字符串。
        /// </summary>
        internal static string ExecuteResult {
            get {
                return ResourceManager.GetString("ExecuteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 App/{0} 的成就数据失败 的本地化字符串。
        /// </summary>
        internal static string GetAchievementDataFailure {
            get {
                return ResourceManager.GetString("GetAchievementDataFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部错误 的本地化字符串。
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 schinese 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ========================================== 的本地化字符串。
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}({1}) 的本地化字符串。
        /// </summary>
        internal static string MaxChange {
            get {
                return ResourceManager.GetString("MaxChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多行结果: 的本地化字符串。
        /// </summary>
        internal static string MultipleLineResult {
            get {
                return ResourceManager.GetString("MultipleLineResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络错误 的本地化字符串。
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无待设置的成就 的本地化字符串。
        /// </summary>
        internal static string NoAchievementEffected {
            get {
                return ResourceManager.GetString("NoAchievementEffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无参数 的本地化字符串。
        /// </summary>
        internal static string NoArgs {
            get {
                return ResourceManager.GetString("NoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无待设置的统计项 的本地化字符串。
        /// </summary>
        internal static string NoStatsEffected {
            get {
                return ResourceManager.GetString("NoStatsEffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML解析失败! 的本地化字符串。
        /// </summary>
        internal static string ParseHtmlFailed {
            get {
                return ResourceManager.GetString("ParseHtmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件作者: Rudokhvist, Chr_, 联系方式: chr@chrxw.com 的本地化字符串。
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱发电: https://afdian.net/@chr233 的本地化字符串。
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐安装 ASFEnhance, 支持自动更新插件 的本地化字符串。
        /// </summary>
        internal static string PluginStandalongMode {
            get {
                return ResourceManager.GetString("PluginStandalongMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置成就{0}, 受影响成就 {1} 个 的本地化字符串。
        /// </summary>
        internal static string SetAchievementResult {
            get {
                return ResourceManager.GetString("SetAchievementResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置统计项{0}, 受影响统计项 {1} 个 的本地化字符串。
        /// </summary>
        internal static string SetStatsResult {
            get {
                return ResourceManager.GetString("SetStatsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 无效参数, 格式为n=x, n为整数, x为整数或d/default(默认值)或i/min(最小值)或a/max(最大值) 的本地化字符串。
        /// </summary>
        internal static string StatsArgumentInvalid {
            get {
                return ResourceManager.GetString("StatsArgumentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无法设置为默认值, 默认值为Null 的本地化字符串。
        /// </summary>
        internal static string StatsCantSetToDefault {
            get {
                return ResourceManager.GetString("StatsCantSetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无法设置为最大值, 最大值为Null 的本地化字符串。
        /// </summary>
        internal static string StatsCantSetToMax {
            get {
                return ResourceManager.GetString("StatsCantSetToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无法设置为最小值, 最小值为Null 的本地化字符串。
        /// </summary>
        internal static string StatsCantSetToMin {
            get {
                return ResourceManager.GetString("StatsCantSetToMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无需更改的统计项 的本地化字符串。
        /// </summary>
        internal static string StatsChangeUnnecessary {
            get {
                return ResourceManager.GetString("StatsChangeUnnecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 具有递增限制的统计项无法设置为更低的值 {3} 的本地化字符串。
        /// </summary>
        internal static string StatsIncrementOnlyLimited {
            get {
                return ResourceManager.GetString("StatsIncrementOnlyLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无法修改被保护的统计项 的本地化字符串。
        /// </summary>
        internal static string StatsIsProtected {
            get {
                return ResourceManager.GetString("StatsIsProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - {0,-3} [{1}] {2}{3}{4}{5} 的本地化字符串。
        /// </summary>
        internal static string StatsItem {
            get {
                return ResourceManager.GetString("StatsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App/{0} 的统计数据列表: 的本地化字符串。
        /// </summary>
        internal static string StatsList {
            get {
                return ResourceManager.GetString("StatsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 设定的值 {3} 超过了最大该变量 {4}, 修改为允许的上/下限 的本地化字符串。
        /// </summary>
        internal static string StatsMaxChangeLimited {
            get {
                return ResourceManager.GetString("StatsMaxChangeLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 找不到此统计项ID 的本地化字符串。
        /// </summary>
        internal static string StatsNotFound {
            get {
                return ResourceManager.GetString("StatsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-{1} [{2}]: 无法设置为{3}, 参数需要为整数 的本地化字符串。
        /// </summary>
        internal static string StatsTargetValueInvalid {
            get {
                return ResourceManager.GetString("StatsTargetValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Id  [最小 当前 最大] 名称 | 🔒受保护🔼仅能增加⚠️最大修改量 的本地化字符串。
        /// </summary>
        internal static string StatsTitle {
            get {
                return ResourceManager.GetString("StatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告信息: 的本地化字符串。
        /// </summary>
        internal static string WarningInfo {
            get {
                return ResourceManager.GetString("WarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
